# Generated by Django 2.1.2 on 2018-10-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userdetail',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='useremail',
            field=models.CharField(default='no email', max_length=30),
        ),
    ]
