# Generated by Django 2.1.2 on 2018-10-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=20),
        ),
    ]
