# Generated by Django 2.1.2 on 2018-11-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('sub_code', models.CharField(max_length=10)),
                ('sub_name', models.CharField(max_length=40)),
                ('T_credits', models.CharField(max_length=5)),
                ('L_credits', models.CharField(max_length=5)),
                ('P_credits', models.CharField(max_length=5)),
            ],
        ),
    ]
