# Generated by Django 2.1.2 on 2018-10-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
    ]
