# Generated by Django 2.1.2 on 2018-10-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapi', '0002_remove_file_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('rollno', models.CharField(max_length=15)),
                ('fine', models.IntegerField()),
            ],
        ),
    ]
