# Generated by Django 2.1.2 on 2018-10-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapi', '0003_libraryfine'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('rollno', models.CharField(max_length=15)),
                ('hostel', models.CharField(max_length=20)),
                ('fine', models.IntegerField()),
            ],
        ),
    ]
