# Generated by Django 2.1.2 on 2018-10-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('year', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('p1StartDate', models.DateTimeField()),
                ('p2StartDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
            ],
        ),
    ]
