# Generated by Django 2.1.2 on 2018-10-30 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='p1EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 30, 5, 6, 42, 346030)),
        ),
    ]
