# Generated by Django 2.1.2 on 2018-10-30 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapi', '0003_auto_20181030_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='p1EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 30, 6, 46, 3, 99332)),
        ),
    ]
