# Generated by Django 2.1.2 on 2018-11-01 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapi', '0004_auto_20181030_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='p1EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 1, 4, 30, 0, 108299)),
        ),
    ]
