# Generated by Django 2.1.2 on 2018-11-03 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapi', '0005_auto_20181101_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='p1EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 3, 4, 55, 7, 145191)),
        ),
    ]
