# Generated by Django 2.1.2 on 2018-11-03 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapi', '0006_auto_20181103_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='reg',
            name='p1EndDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 3, 16, 42, 27, 83830)),
        ),
    ]
